### ISSUE TITLE
Catalina freezes when using BCM94350ZAE

### ISSUE THREAD

**Issue by bangbaew** [acai66/lenovo-miix-520-hackintosh#28]
![5D4E3970-7279-45BF-810C-904F316968B8](https://user-images.githubusercontent.com/29559559/71462152-0306e900-27e5-11ea-8bdf-98632a223a42.jpeg)
**PC:** Miix 520
**OS:** Olarila Catalina 10.15.2 (APFS)
**WLAN Card:** Dell Wireless 1820A

I’ve changed my Intel’s card to a $8 DW1820A (bcm94350zae) and it works, I don’t think Miix 520 have WLAN card whitelist, I used BrcmPatchRAM2.kext but it doesn’t work on Catalina, so I downloaded BrcmPatchRAM3.kext from Acidanthera's [BrcmPatchRAM](https://github.com/acidanthera/BrcmPatchRAM) and I followed configuration guide from Ameeno's [DELL-DW1820A-Drivers](https://github.com/ameeno/DELL-DW1820A-Drivers/blob/master/MacOS%20(Hackintosh)/README.md) to config PCI ID settings under Devices/Properties in Clover Configurator to make the card detected by Catalina.

After that,
**WiFi, Bluetooth and AirDrop works fine**.
But after using the computer for a while, the **system goes freezing**, the clock stops, but only cursor is still movable.

Please help me on this, and I wanna know if $50 bcm94352z works well on Catalina without having much configuration? If it works and not freezing, I might buy a new one. Thanks

**Comment by acai66** [comment]
yes,bcm94352z works well,no more configurations.
