### ISSUE TITLE
How can I change OpenCore default boot OS?

### ISSUE THREAD

**Issue by bangbaew** [acai66/lenovo-miix-520-hackintosh#30]
I’m currently dual booting Windows 10 and Catalina with _OpenCore 0.5.4_ (the release version 2.0 of this repo), everything works fine but the default timeout boot OS is **BOOTCAMP Windows**, how can I change it to **macOS**? 

I’ve tried choosing macOS as **Startup Disk** in _Preferences_ pane but after that, the system freezes when clicking restart button and it doesn’t apply any setting. (Normal system restart works fine)

![7C807C93-7AA4-4128-90F5-1A0956DA38E3](https://user-images.githubusercontent.com/29559559/71767156-a9689200-2f3b-11ea-9cc6-15e9e18cac9f.jpeg)

**Comment by acai66** [comment]
I've updated v2.1. in picker interface, press CTRL and OS INDEX to set default boot entry, or use UP/DOWN keys to switch highlight, then press CTRL + ENTER to boot and set current OS to default entry.

**Comment by bangbaew** [comment]
I’ve updated to 2.1 but Windows can’t be booted anymore, when I boot windows from OpenCore, the Windows circle spins for a sec and loop restart to OpenCore menu again and again, Windows automatic repair also comes up, but it still doesn’t boot to Windows. but release version 2.0 Windows boots up fine.

**Comment by acai66** [comment]
I will update v2.2, you can have a try

**Comment by bangbaew** [comment]
> I will update v2.2, you can have a try

I've tried 2.2, Windows is still unable to boot, it loops to OpenCore boot menu...
and in macOS, if I use Clover, the Energy Saver preferences will have both Battery and Power Adapter tab, but when I use OpenCore, there's only one option which I don't know if it's on Battery or Power Adapter.

**Comment by bangbaew** [comment]
> > I will update v2.2, you can have a try
> 
> I've tried 2.2, Windows is still unable to boot, it loops to OpenCore boot menu...
> and in macOS, if I use Clover, the Energy Saver preferences will have both Battery and Power Adapter tab, but when I use OpenCore, there's only one option which I don't know if it's on Battery or Power Adapter.

![85D15FF8-07A1-412C-8F49-BE8850111272](https://user-images.githubusercontent.com/29559559/76698865-15087180-66da-11ea-925d-cb14afbda209.jpeg)
![CA30F383-BBF9-4FE4-8302-26FE98178471](https://user-images.githubusercontent.com/29559559/76698868-19cd2580-66da-11ea-84be-1f188342ef9d.jpeg)

**Comment by acai66** [comment]
try latest OpenCore or CLOVER.
