### ISSUE TITLE
发现OC引导时，睡眠睡死的问题

### ISSUE THREAD

**Issue by Jeoway** [acai66/lenovo-miix-520-hackintosh#35]
![2020-03-18_15-37-46](https://user-images.githubusercontent.com/59622053/76937106-1bdbf200-692f-11ea-8c6d-76645b2fb0de.png)

**Comment by Jeoway** [comment]
大佬，我这还有个小问题，就是显卡是驱动好了，但是屏幕显示却有些闪烁和水波纹的情况，我用其他的clover精简引导却不会存在屏幕闪烁的这个问题，不知道是啥情况，虽不影响使用，但看着有点难受，不知道大佬屏幕有没有这种情况。

**Comment by acai66** [comment]
已更新配置，如有问题请重开issue
