### ISSUE TITLE
才哥你好,这个版本的voodooI2C貌似有些问题

### ISSUE THREAD

**Issue by onnonn** [acai66/lenovo-miix-520-hackintosh#40]
我的miix510修改后其他均可正常驱动,但是触屏及触屏手势均不能用.我把VoodooI2C.kext,VoodooI2CHID.kext,VoodooPS2Controller.kext换成旧版后触屏正常了.
是新版本兼容性的问题还是我设备的问题呢?

**Comment by acai66** [comment]
你什么版本的系统，我用的驱动是我在10.15下编译的

**Comment by onnonn** [comment]
10.15.4
驱动版本是voodooI2C&nbsp; 2.3
我直接抄的作业，没自己编译



---原始邮件---
发件人: "阿才"<notifications@github.com&gt;
发送时间: 2020年5月26日(周二) 上午8:25
收件人: "acai66/lenovo-miix-520-hackintosh-CLOVER"<lenovo-miix-520-hackintosh-CLOVER@noreply.github.com&gt;;
抄送: "onnonn"<670635118@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [acai66/lenovo-miix-520-hackintosh-CLOVER] 才哥你好,这个版本的voodooI2C貌似有些问题 (#40)




 
你什么版本的系统，我用的驱动是我在10.15下编译的

**Comment by acai66** [comment]
可以直接使用voodooi2c官方编译的驱动，简单修改下voodooi2chid里的一个文件就好了
