### ISSUE TITLE
Big Sur 仍无法安装 && 读卡器驱动可能的解决方案

### ISSUE THREAD

**Issue by miyuanbo** [acai66/lenovo-miix-520-hackintosh#46]
尝试了最新的2.5beta，
1.引导u盘安装原版bigsur安装盘时出现startimage错误，但在config中加入booter-fileset-basesystem可以进入读进度条的阶段，然而会卡，-v显示有进程不断因进程数量过多而退出。
2.如果从系统（10.15.4）直接点击app升级，重启后在opencore会出现一个macOS Install的引导菜单，但无论加不加booter-fileset-basesystem都直接报startimage failed错误。
并且，如果加了booter-fileset-basesystem，也会导致原来的10.15.4也无法启动

另外，关于读卡器，我也是美版miix520，读卡器型号RTS5208，不在sinetek-rtsx支持的型号中。但考虑这个驱动最近更新到2.3版本了，加入了5209的支持，或许可以考虑将5208的id仿冒为5209试试？毕竟这两个型号在windows下共用驱动。

**Comment by acai66** [comment]
暂时可以先在win下用vmware启动硬盘里的mac，在vmware里完成升级过程，再重启用oc引导。据反馈读卡器驱动不稳定，有概率内核崩溃，我换了lte 模块，已经没有sd卡模块了。

**Comment by miyuanbo** [comment]
吃上螃蟹了！才哥nb！
