### ISSUE TITLE
最新版oc已经可以直接引导安装盘

### ISSUE THREAD

**Issue by miyuanbo** [acai66/lenovo-miix-520-hackintosh#47]
经测试，最新版oc（7月8日编译）已经可以直接引导，不需要加booter-fileset-kernel和booter-fileset-basesystem了。

**Comment by miyuanbo** [comment]
又启动了几次，发现有几率卡在lilu.kext引发的kernel panic. 加上booter-fileset-kernel才能继续进系统。目前的oc直接引导还是不太稳定。。。

**Comment by miyuanbo** [comment]
以及，升级beta2的安装盘貌似需要换回fakesmc才能引导，否则会出现smc不支持的提示

**Comment by leopardkk** [comment]
最近升级到beta4的时候报错了，有没有什么经验指导一下

**Comment by leopardkk** [comment]
升级到beta2 时没啥问题，但是以后升级各种问题，升级不上去了

**Comment by acai66** [comment]
持续更新...
