### ISSUE TITLE
Stuck at 14 minutes

### ISSUE THREAD

**Issue by someone12368** [acai66/lenovo-miix-520-hackintosh#57]
Same configuration as yours. Downloaded OC to EFI folder and Boot with one file from the other source. Everything goes well up until 14 minutes remaining. The usb drive stops flashing and system freezes. I have created a 128Gb partition on the same drive for the installation. I believe it freezes when it is supposed to write files on the drive. This happens few minutes after I run.

**Comment by EvilZabanya** [comment]
> Same configuration as yours. Downloaded OC to EFI folder and Boot with one file from the other source. Everything goes well up until 14 minutes remaining. The usb drive stops flashing and system freezes. I have created a 128Gb partition on the same drive for the installation. I believe it freezes when it is supposed to write files on the drive. This happens few minutes after I run.

Your problems happened when you install the MacOS or just finish the installation and try to boot in the MacOS?
I install the MacOS with the OC by original files and successfully boot in the MacOS.Then I change the OC files to this Miix520 files.

**Comment by someone12368** [comment]
Problem was with my SSD, it was not supported. I have successfully installed it on usb SSD. Even better this way because I have more space and speed is quite good, thanks!
